language: r
sudo: false
cache: packages

services:
  - redis-server
env:
 - PKGAPI_VALIDATE=true

r_packages:
  - covr
before_script:
  - R CMD INSTALL .
after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - vimc/orderly
  - reside-ic/pkgapi
  - ropensci/jsonvalidate
  - mrc-ide/rrq

addons:
  apt:
    packages:
      - libv8-dev
      - libapparmor-dev
      - libhiredis-dev
      - redis-server
