language: r
sudo: false
cache: packages

r_packages:
  - covr
before_script:
  - R CMD INSTALL .
after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - vimc/orderly@vimc-3945
  - reside-ic/pkgapi
  - ropensci/jsonvalidate

addons:
  apt:
    packages:
      - libv8-dev
      - libapparmor-dev
