steps:
  - label: ":construction_worker: Build"
    command: docker/build

  - wait

  - label: ":hammer: Test"
    command: docker/test

  - label: ":shipit: Push"
    command: docker/push

  - wait

  # The next 3 steps trigger builds on the large images we use for
  # downstream work: https://buildkite.com/docs/pipelines/trigger-step
  #
  # By default these will trigger only when orderly.server is on
  # master - comment out the "branches:" key to make it always trigger
  #
  # By default these will trigger the master branch on the downstream
  # repo - change the "branch:" key to use a feature branch
  - trigger: "montagu-orderly"
    label: ":rocket: montagu image (from orderly.server) :syringe:"
    branches: "master"
    build:
      branch: master

  - trigger: "ncov-orderly"
    label: ":rocket: ncov image (from orderly.server) :microbe:"
    branches: "master"
    build:
      branch: master

  - trigger: "ebola-orderly"
    label: ":rocket: ebola image (from orderly.server) :biohazard_sign:"
    branches: "master"
    build:
      branch: master

  - trigger: "covid19-forecasts-orderly"
    label: ":rocket: forecasts image (from orderly.server) :nerd:"
    branches: "master"
    build:
      branch: main

  - trigger: "hiv-orderly"
    label: ":rocket: hiv image (from orderly.server) :reminder_ribbon:"
    branches: "master"
    build:
      branch: main
