#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

function cleanup {
    echo "Cleaning up"
    rm -f $PACKAGE_ROOT/docker/Dockerfile.worker
}
trap cleanup EXIT

cat << EOF > $HERE/Dockerfile.worker
FROM $TAG_SHA
ENTRYPOINT ["/usr/local/bin/orderly_worker"]
EOF

docker build --pull \
       -t $TAG_SHA \
       -f docker/Dockerfile \
       $PACKAGE_ROOT

docker build \
       -t $TAG_WORKER_SHA \
       -f docker/Dockerfile.worker \
       $PACKAGE_ROOT

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
docker push $TAG_WORKER_SHA
