#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       -t $TAG_SHA \
       -f docker/Dockerfile \
       --build-arg "BASE_IMAGE_TAG=${ORDERLY_VERSION}" \
       $PACKAGE_ROOT

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
