#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

# Push the human-readable tagged versions here (the SHA versions were
# pushed during build)
docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_BRANCH

docker tag $TAG_WORKER_SHA $TAG_WORKER_BRANCH
docker push $TAG_WORKER_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $TAG_SHA \
                             -c 'echo $ORDERLY_VERSION')
    TAG_VERSION="${PACKAGE_ORG}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
    docker tag $TAG_SHA $TAG_LATEST
    docker tag $TAG_SHA $TAG_VERSION
    docker push $TAG_LATEST
    docker push $TAG_VERSION

    TAG_WORKER_VERSION="${PACKAGE_ORG}/${WORKER_NAME}:${ORDERLY_VERSION}"
    docker tag $TAG_WORKER_SHA $TAG_WORKER_LATEST
    docker tag $TAG_WORKER_SHA $TAG_WORKER_VERSION
    docker push $TAG_WORKER_LATEST
    docker push $TAG_WORKER_VERSION
fi
