#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

# Push the human-readable tagged versions here (the SHA versions were
# pushed during build)
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $APP_PRIVATE_COMMIT_TAG \
                             -c 'echo $ORDERLY_VERSION')
    TAG_VERSION="${PACKAGE_ORG}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
    TAG_LATEST="${PACKAGE_ORG}/${PACKAGE_NAME}:latest"
    docker tag $TAG_BRANCH $TAG_LATEST
    docker push $TAG_LATEST
    docker push $TAG_VERSION
fi
