#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

# Push the human-readable tagged versions here (the SHA versions were
# pushed during build)
docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    ORDERLY_VERSION=$(docker run --rm --entrypoint bash \
                             $TAG_BRANCH \
                             -c 'echo $ORDERLY_VERSION')
    TAG_VERSION="${PACKAGE_ORG}/${PACKAGE_NAME}:${ORDERLY_VERSION}"
    TAG_LATEST="${PACKAGE_ORG}/${PACKAGE_NAME}:latest"
    docker tag $TAG_BRANCH $TAG_LATEST
    docker push $TAG_LATEST
    docker push $TAG_VERSION
fi
